[package]
name = "rpc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio ={ workspace = true}
bincode = "1"