[package]
name = "rpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rpc-core = { path = "../rpc-core" }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0"
async-trait = "0.1.50"
