[package]
name = "rpc-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rpc-core = { path = "../rpc-core" }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0"